visit -cli -nowin -s movie_loop_script.py 0 layer1 rm 6
visit -cli -nowin -s movie_loop_script.py 0 layer19 rm 6
visit -cli -nowin -s movie_loop_script.py 0 3D rm 6
visit -cli -nowin -s movie_loop_script.py 0 3Dslice rm 6
visit -cli -nowin -s movie_loop_script.py 1 layer1 rm 6
visit -cli -nowin -s movie_loop_script.py 1 layer19 rm 6
visit -cli -nowin -s movie_loop_script.py 1 3D rm 6
visit -cli -nowin -s movie_loop_script.py 1 3Dslice rm 6
visit -cli -nowin -s movie_loop_script.py 2 layer1 rm 6
visit -cli -nowin -s movie_loop_script.py 2 layer19 rm 6
visit -cli -nowin -s movie_loop_script.py 2 3D rm 6
visit -cli -nowin -s movie_loop_script.py 2 3Dslice rm 6
